name: "Peercoin Core"
version: "0.15.10"
slug: "peercoin"
description: "Peercoin Core ARM64 avec minting continu"
arch:
  - aarch64

startup: services
boot: auto
init: false

map:
  - type: share
    read_only: false

ports:
  9901/tcp: 9901

ports_description:
  9901/tcp: "Port réseau Peercoin"

options:
  rpcuser: "ppc_rpc"
  rpcpassword: ""

  minting: false

schema:
  rpcuser: str
  rpcpassword: password
  #walletname: str
  #walletpassphrase: password
  minting: bool
