name: "Peercoin Core"
version: "0.15.11"
slug: "peercoin"
description: "Peercoin Core ARM64 avec minting continu"
url: "https://github.com/spartiate74/peercoin-haos-addon"
arch:
  - aarch64

startup: services
boot: auto
init: false

options:
  rpcuser: "ppc_rpc"
  rpcpassword: "CHANGE_MOI_RPC_PASSWORD"
  walletname: "android-legacy"
  walletpassphrase: "CHANGE_MOI_WALLET_PASSPHRASE"
  minting: true

schema:
  rpcuser: str
  rpcpassword: password
  walletname: str
  walletpassphrase: password
  minting: bool

ports:
  9901/tcp: 9901

ports_description:
  9901/tcp: "Port réseau Peercoin"

image: "spartiate74/{arch}-peercoin"
